app:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5555/tms_vietnam"
    username: "tms_admin"
    password: "Usfy3siOO%fX"
    hikari-config:
      pool-name: app-pool
      maximum-pool-size: 30
      minimum-idle: 5

spring:
  redis:
    server: 27.71.226.237
    port: 9107
    password: Tm5@P@ssw0rd

logging:
  level:
    com.tms: info

inmemory:
  datasource:
    jdbcUrl: "jdbc:sqlite::memory:"
    username: "sa"
    password: "sa"
    pool-name: memory-pool
    maximum-pool-size: 30
    minimum-idle: 5